- name: Deploy Smart Exam Seating App
  hosts: local
  become: yes

  tasks:

    - name: Stop old container
      command: docker rm -f seating-app
      ignore_errors: yes

    - name: Build Docker image
      command: docker build -t seating-app .
      args:
        chdir: /home/prajan/SmartExamSystem

    - name: Run container with volume (PERSIST DATA)
      command: docker run -d -p 5000:5000 -v /home/prajan/SmartExamSystem/students.csv:/app/students.csv --name seating-app seating-app
